### ISSUE TITLE
Hangs on 'localhost contacted. Waiting for reply...'

### ISSUE THREAD

**Issue by PeterDaveHello** [alberthier/git-webui#11]
It works pretty good on one of my computer, but keep getting `localhost contacted. Waiting for reply...` on another one. Any suggestions?

**Comment by alberthier** [comment]
Can you give me some more details:
Which OS are you using ?
What is your Python version ?
What is your git version ?
What browser are you using (and which version) ?

**Comment by PeterDaveHello** [comment]
Sure.
This is the env of the not working machine:
> Distributor ID: Debian
> Description:    Debian GNU/Linux 8.1 (jessie)
> Release:        8.1
> Codename:       jessie
> Linux ftp 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 GNU/Linux
> Python 2.7.9
> Python 3.4.2
> git version 2.1.4

This is my browser on another computer
> firefox 39.0+build5-0ubuntu0.14.04.1

But I think it has nothing to do with my browser, I use the same browser on the same machine.

Or did I miss something? Thanks!

**Comment by alberthier** [comment]
I'll install jessie in a VM and try to reproduce.

**Comment by PeterDaveHello** [comment]
Thank you very much @alberthier

**Comment by alberthier** [comment]
I couldn't reproduce the issue :(
The only scenario where I got a similar situation is when I entered the wrong IP in the browser address bar.

If I understand correctly, you are running git-webui on a Debian machine and try to access it from another machine, right ?

On this other machine, are you sure you enter the IP address of the one running git-webui ? In your first comment, you mention 'localhost', but it should be someting like http://<ip-of-the-debian-machine>:8000

**Comment by PeterDaveHello** [comment]
> If I understand correctly, you are running git-webui on a Debian machine and try to access it from another machine, right ?
Right
> On this other machine, are you sure you enter the IP address of the one running git-webui ? In your first comment, you mention 'localhost', but it should be someting like http://:8000
Of course, but I think it hangs on the server side, not client issue.

**Comment by sarink** [comment]
I finally figured this one out. For me, at least, the problem is that webui is trying to start a browser (nice feature, but I'm using this on a headless virtual machine, and the only web browser I have installed is phantomjs).

Using the --no-browser argument fixed it.

**Comment by alberthier** [comment]
OK, so the issue is fixed for me.
The browser autostart is a nice feature and fits well the common use case.
It depends on Python's webbrowser module.

**Comment by PeterDaveHello** [comment]
Maybe we can add it in readme?

**Comment by arnavmehta7** [comment]
Hey I am getting same issue. Whats the solution? --no-browser doesn't works anymore :\
