### ISSUE TITLE
Versioned releases

### ISSUE THREAD

**Issue by tomas** [alberthier/git-webui#13]
Hi -- great work!

I just submitted [a formula for Homebrew](https://github.com/Homebrew/homebrew/pull/42332) but apparently they only accept stable, versioned releases for the package tarballs. Would it be possible to get a versioned, tagged release so we can get the brew folks to accept the PR?

Thanks again.

**Comment by alberthier** [comment]
Up to now I didn't feel the need for versions as I consider master as 'always' stable.
But integration in homebrew is a good reason to start to use version numbers.
I tagged the current version as 1.0.0

**Comment by tomas** [comment]
Slick. I'll update the formula and let you know if there's anything else.

**Comment by alberthier** [comment]
OK, thanks :)
