### ISSUE TITLE
Unable to remotly pull

### ISSUE THREAD

**Issue by mtx-z** [alberthier/git-webui#17]
Hi, really nice tool ! Thanks :)
Setup and initials configurations are working great. 

Only thing, I cannot success to pull from my local machine onto my server. 
On "git pull http//my_ip:8000/",  GIT answer that repo dont exist or is not a repo. 

But i can access the interface using http//my_ip:8000/. Any thing i've missed ?

thx a lot !!

**Comment by alberthier** [comment]
This should definitively work

Here are a few things you can try:

1. I guess it's a typo, but you forgot the colon in the URLs in your post `http//my_ip` => `http://my_ip`
1. Ensure the URL contains the trailing slash
1. Try to clone/pull the repository on the same machine than the one running git-webui (`git clone http://localhost:8000/`). If this works, it may be network configuration issue
1. Check the git version on your server. I didn't test git-webui on old git versions

**Comment by alberthier** [comment]
After investigation, it seems to be an issue with git-http-backend in recent git versions
adding `have_fork = False` as class variable in `git-webui` script seems to help but raises other issues on some repositories.

**Comment by mtx-z** [comment]
Hey Alberthier. 
Thanks for still carring about :) i'll try adding the '`have_fork`' variable and see if i got result. 

Are you planning to fix this in a next release ?

**Comment by alberthier** [comment]
Yes, I'll definitively fix this issue as it's one of the main feature of this project :)
I reproduce it, but I don't know how to fix it reliably.
I tested with git 2.1.4 : pull & clone work properly
With git 2.5.4 : the feature is broken.

I'll probably release a version with the `have_fork` hack but it doesn't seem to be a complete solution
