### ISSUE TITLE
Port 8000 buzy port 8001 does not work.

### ISSUE THREAD

**Issue by JostCrow** [alberthier/git-webui#31]
Port 8000 is already in use, trying another one
Serving at http://localhost:8001
127.0.0.1 - - [03/May/2017 15:56:48] code 404, message File not found
127.0.0.1 - - [03/May/2017 15:56:48] "GET /dashboard/ HTTP/1.1" 404 -

![page-shot-2017-5-3 error response](https://cloud.githubusercontent.com/assets/390575/25664365/b4b84452-301a-11e7-8f6a-96b62a1951fb.png)

**Comment by alberthier** [comment]
According to your log, you try to access to http://localhost:8001/dashboard/ which isn't a git-webui url
You may have used port 8001 for another server and your browser kept the redirection to /dashboard/ in cache.
try to clear your cache or force http://localhost:8001/index.html
